Vagrant.configure("2") do |config|
  config.vm.box = "QuickSquirrel/CentOS-8-LAMP"
  config.vm.hostname = "TASK-01-1"


  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081

 config.vm.provision "shell", inline: <<-SHELL

   mkdir /var/www/html/demosite-static /var/www/html/demosite-php
   cp -f /vagrant/index.html /var/www/html/demosite-static/
   cp -f /vagrant/index.php /var/www/html/demosite-php/
   cp -f /vagrant/vh.conf /etc/httpd/conf.d/
   echo "Listen 8080" >> /etc/httpd/conf/httpd.conf
   echo "Listen 8081" >> /etc/httpd/conf/httpd.conf

   systemctl restart httpd
 SHELL

 config.vm.provider "virtualbox" do |vb|
   vb.memory = "1024"
 end

end
