Vagrant.configure("2") do |config|
  config.vm.box = "QuickSquirrel/CentOS-8-LAMP"
  config.vm.hostname = "TASK-03-1"

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.become = true
  end
end
