- name: Install Jenkins
  vars:
    jenkins_user: admin
    jenkins_passw: admin
    jenkins_url: http://localhost:8080
  hosts: localhost
  become: true
  tasks:
    - name: Install packeges all other
      apt:
        pkg:
        - daemon
        - git
        - build-essential 
        - python-pip-whl
        - python3-pip
        - openjdk-11-jdk
        - gnupg2
        state: present
        update_cache: yes

    - name: Install Python
      pip:
        name:
          - python-jenkins
          - lxml

    - name: Install key for repo
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
    
    - name: Add repo to repofile
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
        update_cache: yes
 
#    - name: Make dir for jenkins service reconfigeration 
#      file:
#        path: /lib/systemd/system/jenkins.service.d
#        state: directory

#    - name: Create file for jenkins service
#      copy:
#        dest: /lib/systemd/system/jenkins.service.d/st-timeout.conf
#        content: |
#          [Service]
#          TimeoutStartSec=180

    - name: Install Jenkins
      apt:
        pkg:
        - jenkins
        state: present
      ignore_errors: yes
 
# python3.7 -m pip install jmespath


#not work in docker

#    - name: Stop Jenkins service
#      service:
#        name: jenkins
#        state: stopped

#    - name: reload systemd
#      systemd:
#        daemon_reload: yes

    - name: Make dirs
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
      with_items:
        - /var/lib/jenkins/users/admin_8133878285141068281
        - /var/lib/jenkins/jobs/GoPipeline
 
    - name: Copy config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        owner: jenkins
        group: jenkins
        force: yes
      with_items:
        - { src: "/tmp/jenkins/files/users/users.xml", dst: "/var/lib/jenkins/users/" }
        - { src: "/tmp/jenkins/files/users/admin_8133878285141068281/config.xml", dst: "/var/lib/jenkins/users/admin_8133878285141068281/" }
        - { src: "/tmp/jenkins/files/config.xml", dst: "/var/lib/jenkins/" }
        - { src: "/tmp/jenkins/files/locale.xml", dst: "/var/lib/jenkins/" }
        - { src: "/tmp/jenkins/files/credentials.xml", dst: "/var/lib/jenkins/" }
        - { src: "/tmp/jenkins/files/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml", dst: "/var/lib/jenkins/" }
        - { src: "/tmp/jenkins/files/jobs/GoPipeline/config.xml", dst: "/var/lib/jenkins/jobs/GoPipeline/" }
  
    - name: Disable start wizard
      lineinfile:
         path: "{{ item.path }}"
         state: present
         regexp: "{{ item.exp }}"
         line: "{{ item.n_ln }}"
      with_items:
#        - { path: "/lib/systemd/system/jenkins.service", exp: '^Environment="JAVA_OPTS=-Djava.awt.headless=true"', n_ln: 'Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration=false"' }
#        - { path: "/lib/systemd/system/jenkins.service", exp: '^Environment="JAVA_OPTS=-Djava.awt.headless=true"', n_ln: 'Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"' }
        - { path: "/etc/default/jenkins", exp: '^JAVA_ARGS="-Djava.awt.headless=true"', n_ln: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"' }

#    - name: reload systemd
#      systemd:
#        daemon_reload: yes

# not work in docker
#    - name: Start Jenkins service
#      service:
#        name: jenkins
#        state: started

    - name: Start jenkins
      sysvinit: 
        name: jenkins
        state: started
        enabled: yes


#    - name: Wait for Jenkins to start up
#      uri:
#        url: http://localhost:8080
#        status_code: 200
#        timeout: 5
#     register: jenkins_service_status
#     # Keep trying for 5 mins in 5 sec intervals
#     retries: 60
#     delay: 5
#     until: >
#       'status' in jenkins_service_status and
#       jenkins_service_status['status'] == 200

    - name: Sleep for 180 seconds and continue with play
      wait_for:
        timeout: 180
      delegate_to: localhost

    - name: Install plugin
      jenkins_plugin:
        name: "{{ item }}"
        url_username: "{{ jenkins_user }}"
        url_password: "{{ jenkins_passw }}"
        url: "{{ jenkins_url }}"
        with_dependencies: yes
      with_items:
        - locale
        - github
        - golang
        - nexus-artifact-uploader
        - timestamper 
        - pipeline
        - pipeline-stage-view
        - pipeline-github-lib
        - pipeline-build-step
        - workflow-basic-steps
        - build-pipeline-plugin
        - workflow-aggregator
        - github-branch-source
        - workflow-cps
        - ssh
        - ssh-build-agents
        - workflow-aggregator
        - workflow-durable-task-step
        - pipeline-utility-steps
        - ssh-steps
        - pipeline-stage-step
        - docker-workflow
        - docker-plugin
#      ignore_errors: yes
      register: plugin_result
      until: plugin_result is success
      retries: 5   # repeat 5-th times
      delay: 5     # delay 5 sec betwin retries
      
#    - name: Restart Jenkins service
#      service:
#        name: jenkins
#        state: restarted

#    - name: Create build
#      community.general.jenkins_build:
#        name: "gobuild"
#        build_number: 1
#        state: present
#        user: "{{ jenkins_user }}"
#        password: "{{ jenkins_passw }}"
#        url: "{{ jenkins_url }}"
