version: '3'

services:
  nexus:
    build:
      dockerfile: Dockerfile.Nexus
    image: nexus
    container_name: nexus
    ports:
    - 81:8081
    networks:
    - net
    deploy:
      resources:
        limits:
          memory: 2048m


  jenkins:
    build:
      dockerfile: Dockerfile.Jenkins
    image: jenkins
    container_name: jenkins
    ports:
    - 80:8080
    networks:
    - net
    deploy:
      resources:
        limits:
          memory: 1024m



networks:
  net: {}